val1 = int(input("Enter large number: "))
val2 = int(input("Enter small number: "))

print(val1 + val2)
print(val1 - val2)
print(val1 * val2)
print(val1 / val2)
print(val1 // val2)
print(val1 % val2)
print(val1 ** val2)
